// Generated by 'unplugin-vue-auto-img'
// We suggest you to commit this file into source control
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly IDog: typeof import('/src/assets/images/dog.png')['default']
  }
}

export {}
